# Generated by Django 6.0.3 on 2026-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_alter_quiz_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="country_code",
            field=models.CharField(default="+91", max_length=8),
        ),
        migrations.AlterField(
            model_name="registration",
            name="mobile",
            field=models.CharField(max_length=20),
        ),
    ]
